enum REST_VERBS {
  GET = "GET",
  POST = "POST",
  PUT = "PUT",
  DELETE = "DELETE",
  PATCH = "PATCH",
}

enum HTTP_STATUS_CODES {
  OK = 200,
  CREATED = 201,
  ACCEPTED = 202,
  NO_CONTENT = 204,
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  METHOD_NOT_ALLOWED = 405,
  CONFLICT = 409,
  INTERNAL_SERVER_ERROR = 500,
  NOT_IMPLEMENTED = 501,
}

enum HTTP_HEADERS {
  CONTENT_TYPE = "Content-Type",
  ACCEPT = "Accept",
  AUTHORIZATION = "Authorization",
}

enum HTTP_CONTENT_TYPES {
  APPLICATION_JSON = "application/json",
}

export { REST_VERBS, HTTP_STATUS_CODES, HTTP_HEADERS, HTTP_CONTENT_TYPES };
