#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

set -e

yarn lint-staged

if (git diff --name-only --cached | grep -e 'cdk' -e 'shared/graphql'); then
    yarn workspace cdk update-snapshot
    git add cdk/lib/__snapshots__/
fi

if (git diff --name-only --cached | grep 'yarn.lock'); then
    yarn dedupe
    git add yarn.lock
    yarn workspace client analyze-main-client-bundle
fi

yarn graphql-refresh
yarn type-check
