#!/bin/sh
echo "Running pre-commit hook"

. "$(dirname "$0")/_/husky.sh"

set -e

fnm use || true
nvm use || true

corepack enable
yarn lint-staged

if (git diff --name-only --cached | grep -e 'cdk' -e 'shared/graphql'); then
    yarn update-snapshot
    git add cdk/lib/__snapshots__/
fi

if (git diff --name-only --cached | grep 'yarn.lock'); then
    yarn dedupe
    git add yarn.lock
    yarn workspace client analyze-main-client-bundle
fi

yarn graphql-refresh
yarn type-check
